print("Welcome to the interactive persona Data Collector !")
print ()
name =input ("Please enter your name :" )
age =int(input("Please enter your age :"))
height =float(input ("Please enter your height in meters :"))
number =int(input("Please enter you favourite number :"))
print ()
print("Thank you ! Here is the infromation we collected:")
print ()
print (f"name {name}(type: {type(name)}, Memory address {id(name)})")
print (f"age {age}(type : {type(age)}), Memery address {id(age)}")
print(f"height {height},{(type(height))},Memery address {id(height)}")
print(f"number {number},{(type(number))},Memory address {id(number)}")
print()
birth_year=2026-age
print (f"Your Birth year is Approximateyl : {birth_year} (Based on your age of {age})")
print()
print ("Thank you for using the Personal Data Collector. Goodbye !")